---
- name: Copy requirements.txt
  ansible.builtin.copy:
    src: pip/requirements.txt
    dest: "/home/vagrant/requirements.txt"
    mode: 'u=rwx,g+x'

- name: Install python packages for Torcs Agents
  shell:
    pip install --upgrade pip -r "/home/vagrant/requirements.txt"
    
# MultiAgentTORCS

- name: Check if MultiAgentTORCS directory exists
  stat:
    path: "/home/vagrant/MultiAgentTORCS"
  register: multi_agent_torcs_dir

- name: Copy MultiAgentTORCS
  ansible.builtin.copy:
    src: MultiAgentTORCS
    dest: /home/vagrant/torcs/MultiAgentTORCS
    mode: 'u=rwx,g+x'
  when: multi_agent_torcs_dir.stat.exists == false

# torcs-node-client

- name: Check if torcs-node-client directory exists
  stat:
    path: "/home/vagrant/torcs-node-client"
  register: torcs-node-client_torcs_dir

- name: Git checkout MultiAgentTORCS
  ansible.builtin.git:
    repo: https://github.com/wayneparrott/torcs-node-client
    dest: "/home/vagrant/torcs-node-client"