#!/usr/bin/env ansible-playbook
---
- hosts: torcs
  connection: ssh
  become: False
  gather_facts: True
  roles:
    - time-and-locale
    - commands
    - zsh
    - gcc
    - git
    - zip
    - dist-upgrade
    - packages
    - libs