# https://github.com/vog3lm/torcs-1.3.7
---
- name: Update zshrc for plib
  become: False
  ansible.builtin.blockinfile:
    path: /home/vagrant/.zshrc
    block: | 
      export CFLAGS='-fPIC'
      export CPPFLAGS='\$CFLAGS'
      export CXXFLAGS='\$CFLAGS'
      cd /vagrant

- name: Check if torcs directory exists
  stat:
    path: "/home/vagrant/torcs"    
  register: torcs_dir

- name: Git checkout torcs
  become: False
  ansible.builtin.git:
    repo: https://github.com/fmirus/torcs-1.3.7.git
    dest: "/home/vagrant/torcs"
  when: torcs_dir.stat.exists == false

- name: configure torcs-server
  become: True
  ansible.builtin.shell:
    cmd: ./configure
    chdir: /home/vagrant/torcs

- name: make torcs-server
  become: False
  community.general.make:
    chdir: /home/vagrant/torcs
    
- name: make install torcs-server
  become: True
  community.general.make:
    chdir: /home/vagrant/torcs
    target: install

- name: make datainstall torcs-server
  become: True
  community.general.make:
    chdir: /home/vagrant/torcs
    target: datainstall

# https://github.com/abhisheknaik96/MultiAgentTORCS

- name: Unarchive scr-client-cpp.tgz
  ansible.builtin.unarchive:
    src: tar/scr-client-cpp.tgz
    dest: '/home/vagrant/torcs'

- name: make client scr-client-cpp
  community.general.make:
    chdir: /home/vagrant/torcs/scr-client-cpp
    params:
      NUM_THREADS: 4